### ISSUE TITLE
Mongo connection issue

### ISSUE THREAD

**Issue by bradgowland** [WebAudioBoys/tbd-2#40]
Something happens and mongo can't connect on first attempt. Not a big problem, but any crash means we lose all sessions on the Zone. Should either fix this, or store sessions on the server for recovery.

Might be worth having a compressed session object stored on the server anyway that we query on startup to recover any sessions. But in the short term error catching probably more feasible.

Full console error:
```
/Users/bgowland/Documents/GitHub/tbd-2/node_modules/mongodb/lib/mongo_client.js:802
          throw err;
          ^
MongoNetworkError: failed to connect to server [ds117888.mlab.com:17888] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds117888.mlab.com ds117888.mlab.com:17888]
    at null.<anonymous> (/Users/bgowland/Documents/GitHub/tbd-2/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:503:11)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/bgowland/Documents/GitHub/tbd-2/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:326:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/bgowland/Documents/GitHub/tbd-2/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)```

**Comment by bradgowland** [comment]
haha whoops I think this is just because I lost internet connection running on localhost
